# Generated by Django 5.2.8 on 2025-12-06 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('trade', models.CharField(choices=[('PLUMBER', 'Sanitär & Heizung'), ('ELECTRICIAN', 'Elektrik'), ('PAINTER', 'Maler & Lackierer'), ('CARPENTER', 'Tischler & Schreiner'), ('GARDENER', 'Garten & Landschaftsbau'), ('OTHER', 'Sonstiges')], default='OTHER', max_length=50, verbose_name='Gewerbe')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Postleitzahl')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='Ausführungsdatum')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis (€)')),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('BOOKED', 'Gebucht'), ('COMPLETED', 'Erledigt'), ('CANCELLED', 'Storniert')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Kunde')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Handwerker')),
            ],
            options={
                'verbose_name': 'Auftrag',
                'verbose_name_plural': 'Aufträge',
                'ordering': ['-created_at'],
            },
        ),
    ]
