# Generated by Django 4.2.27 on 2025-12-12 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('trade', models.CharField(choices=[('PLUMBER', 'Sanitär & Heizung'), ('ELECTRICIAN', 'Elektrik'), ('PAINTER', 'Maler & Lackierer'), ('CARPENTER', 'Tischler & Schreiner'), ('GARDENER', 'Garten & Landschaftsbau'), ('OTHER', 'Sonstiges')], default='OTHER', max_length=50, verbose_name='Gewerbe')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Postleitzahl')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='Verfügbar ab')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Startpreis (€)')),
                ('status', models.CharField(choices=[('OPEN', 'Aktiv'), ('PAUSED', 'Pausiert')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to=settings.AUTH_USER_MODEL, verbose_name='Handwerker')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('CONFIRMED', 'Bestätigt'), ('COMPLETED', 'Erledigt'), ('CANCELLED', 'Storniert')], default='PENDING', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Vereinbarter Preis')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_received', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
